WordPress/Controllers/WordPressController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WordPress.Content.Models;
using WordPress.Content.Providers;
using WordPress.Content.ViewModels;

namespace WordPress.Controllers
{
    public class WordPressController : Controller
    {
        #region Declaraions
        //declarations
        private static WPContentProvider _wpContentSvc = new WPContentProvider();
        private static int idNumberValue;
        private static string TopNavMenuId = ConfigurationManager.AppSettings["TopNavMenuID"];
        private static string FootNavMenuId = ConfigurationManager.AppSettings["FootNavMenuID"];
        public enum MenuOptions
        {
            TOPNAV,
            FOOTNAV
        }
        #endregion

        #region Constructors
        //contructors
        private WPContentViewModel contentViewModel = new WPContentViewModel()
        {
            TopNavMenuModel = GetMenuContentCollection(TopNavMenuId),
            FooterNavMenuModel = GetMenuContentCollection(FootNavMenuId)
        };
        #endregion

        #region Public Methods
        // GET: WordPress

        /// <summary>
        /// Method is used as a default for retrieving the homepage
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Index(string id)
        {
            contentViewModel.PageModel = 

                //detect whether the id is an int or a string
                Int32.TryParse(id, out idNumberValue)
                ? (WPPostPageModel)

                //if the id is an int, apply the "include" filter
                    _wpContentSvc.GetWPContent(WPEnums.ContentTypes.PAGE, new Dictionary<WPEnums.Filters, string>()
                    {
                        {WPEnums.Filters.include, WPEnums.Filters.include.Apply(idNumberValue.ToString())}
                    })
                : (WPPostPageModel)

                //if the id is a string, apply the "slug" filter
                    _wpContentSvc.GetWPContent(WPEnums.ContentTypes.PAGE,
                    new Dictionary<WPEnums.Filters, string>()
                    {
                        {WPEnums.Filters.slug, WPEnums.Filters.slug.Apply(id)}
                    });

            //set the viewBag title for the home page (which is the only page that uses the Index action)
            ViewBag.Title = "WordPress 4 .NET";

            return View("~/Views/Content/WPPage.cshtml", contentViewModel);
        }

        /// <summary>
        /// Method is used for retrieving Page content
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Page(string id)
        {
            contentViewModel.PageModel =

                //detect whether the id is an int or a string
                Int32.TryParse(id, out idNumberValue)
                ? (WPPostPageModel)

                    //if the id is an int, apply the "include" filter
                    _wpContentSvc.GetWPContent(WPEnums.ContentTypes.PAGE, new Dictionary<WPEnums.Filters, string>()
                    {
                        {WPEnums.Filters.include, WPEnums.Filters.include.Apply(idNumberValue.ToString())}
                    })
                : (WPPostPageModel)

                    //if the id is a string, apply the "slug" filter
                    _wpContentSvc.GetWPContent(WPEnums.ContentTypes.PAGE,
                    new Dictionary<WPEnums.Filters, string>()
                    {
                        {WPEnums.Filters.slug, WPEnums.Filters.slug.Apply(id)}
                    });

            //set the viewBag title for the home page, otherwise, the viewBag title is set on the View 
            if (id.Contains("home"))
            {
                ViewBag.Title = "WordPress 4 .NET";
            }

            return View("~/Views/Content/WPPage.cshtml", contentViewModel);
        }

        /// <summary>
        /// Method is used for retreiving Post content
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Post(string id)
        {
            contentViewModel.PostModel =

                //detect whether the id is an int or a string
                Int32.TryParse(id, out idNumberValue)
                ? (WPPostPageModel)

                    //if the id is an int, apply the "include" filter
                    _wpContentSvc.GetWPContent(WPEnums.ContentTypes.POST,
                    new Dictionary<WPEnums.Filters, string>()
                    {
                        { WPEnums.Filters.include, WPEnums.Filters.include.Apply(idNumberValue.ToString())},
                        { WPEnums.Filters._embed, WPEnums.Filters._embed.Apply("_embed")}
                    })
                : (WPPostPageModel)

                    //if the id is a string, apply the "slug" filter
                    _wpContentSvc.GetWPContent(WPEnums.ContentTypes.POST,
                    new Dictionary<WPEnums.Filters, string>()
                    {
                        { WPEnums.Filters.slug, WPEnums.Filters.slug.Apply(id)},
                        { WPEnums.Filters._embed, WPEnums.Filters._embed.Apply("_embed")}
                    });

            //the viewBag title can be set on the view
            return View("~/Views/Content/WPPost.cshtml", contentViewModel);
        }

        /// <summary>
        /// Method is used when other controllers want to inherit from WPController and use the Menu capabilities
        /// </summary>
        /// <param name="menuOption"></param>
        /// <returns></returns>
        public WPMenuModel Menu(MenuOptions menuOption)
        {
            var contentModel = new WPMenuModel();

            switch (menuOption)
            {
                case MenuOptions.TOPNAV:
                    contentModel = GetMenuContentCollection(TopNavMenuId);
                    break;
                case MenuOptions.FOOTNAV:
                    contentModel = GetMenuContentCollection(FootNavMenuId);
                    break;
                default:
                    contentModel = GetMenuContentCollection(TopNavMenuId);
                    break;
            }

            return contentModel;
        }

        /// <summary>
        /// Method is used for retrieving a collection of posts under the category nomination
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Category(string id)
        {
            contentViewModel.PostCategories =

                //detect whether the id is an int or a string
                //both implementation use the "_embed" filter, which is required for featuredMedia, wpterms, authors
                Int32.TryParse(id, out idNumberValue)
                   ? (WPPostCategories)

                       //if the id is an int, apply the "categories" filter
                       _wpContentSvc.GetWPContent(WPEnums.ContentTypes.POSTCATEGORY,
                       new Dictionary<WPEnums.Filters, string>()
                       {
                        { WPEnums.Filters.categories, WPEnums.Filters.categories.Apply(idNumberValue.ToString())},
                        { WPEnums.Filters._embed, WPEnums.Filters._embed.Apply("_embed")}
                       })
                   : (WPPostCategories)

                       //if the id is a string, apply the "filter" params
                       _wpContentSvc.GetWPContent(WPEnums.ContentTypes.POSTCATEGORY,
                       new Dictionary<WPEnums.Filters, string>()
                       {
                        { WPEnums.Filters.filter, WPEnums.Filters.filter.Apply(id,"category_name")},
                        { WPEnums.Filters._embed, WPEnums.Filters._embed.Apply("_embed")}
                       });

            //the viewBag title can be set on the view
            return View("~/Views/Content/WPCategory.cshtml", contentViewModel);
        }

        /// <summary>
        /// Method is used for retrieving a collection of posts under the author nomination
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Author(string id)
        {
            contentViewModel.PostCategories =

                //detect whether the id is an int or a string
                Int32.TryParse(id, out idNumberValue)
                   ? (WPPostCategories)

                       //if the id is an int, apply the "categories" filter
                       _wpContentSvc.GetWPContent(WPEnums.ContentTypes.POST,
                       new Dictionary<WPEnums.Filters, string>()
                       {
                        { WPEnums.Filters.categories, WPEnums.Filters.categories.Apply(idNumberValue.ToString())},
                        { WPEnums.Filters._embed, WPEnums.Filters._embed.Apply("_embed")}
                       })
                   : (WPPostCategories)

                       //if the id is a string, apply the "filter" params
                       _wpContentSvc.GetWPContent(WPEnums.ContentTypes.POSTCATEGORY,
                       new Dictionary<WPEnums.Filters, string>()
                       {
                        { WPEnums.Filters.filter, WPEnums.Filters.filter.Apply(id,"author")},
                        { WPEnums.Filters._embed, WPEnums.Filters._embed.Apply("_embed")}
                       });

            //the viewBag title can be set on the view
            return View("~/Views/Content/WPCategory.cshtml", contentViewModel);
        }
        #endregion

        #region Private Methods
        /// <summary>

WordPress/Views/MVC/_MVCHeader.cshtml
@using WordPress.Content.Models
@using WordPress.Controllers
@using WordPress.Content.ViewModels
@model WordPress.Content.ViewModels.WPContentViewModel

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="header-sticky-height"></div>
        <div class="header">
            <div class="row">
                <div class="logo" data-margin-top="6px" data-margin-bottom="8px" data-margin-left="0px" data-margin-right="0px">
                    <a class="logo-link" href="">
                        <!-- sticky header logo -->
                    </a>
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("WordPress 4 .NET", "Index", "WordPress", new {area = ""}, new {@class = "navbar-brand"})
                </div>
                @if (@Model.TopNavMenuModel != null && Model.TopNavMenuModel.items != null && Model.TopNavMenuModel.items.Any())
                {
                    <div class="navbar-collapse collapse">
                        @*<div @Model.TopNavMenuModel.styles.GetSafeProperty("divTopMenuClass")>*@
                        <!--First Level Menu-->
                        <ul @Html.Raw(Model.TopNavMenuModel.styles.GetSafeProperty("ulTopMenuId")) @Html.Raw(Model.TopNavMenuModel.styles.GetSafeProperty("ulTopMenuClass"))>
                            @foreach (var menuItem in Model.TopNavMenuModel.items)
                            {
                                if (menuItem.object_slug != null)
                                {
                                    var routeValues = new RouteValueDictionary();
                                    routeValues.Add("id", menuItem.object_slug);
                                    var menuItemId = menuItem.id.ToString();

                                    <li @menuItem.styles.GetSafeProperty("liBaseMenuId" + "-" + @menuItemId) @Html.Raw(@menuItem.styles.GetSafeProperty("liBaseMenuClass" + "-" + @menuItemId))>
                                        @*@Html.ActionLink(menuItem.title, menuItem.type_label, routeValues)*@

                                        @if (menuItem.children == null)
                                        {
                                            @Html.ActionLink(menuItem.title, menuItem.type_label, routeValues)
                                        }
                                        else
                                        {
                                            <!--Second Level Menu-->
                                            <a class="dropdown-toggle" role="button" aria-expanded="false" href="@Url.RouteUrl(routeValues)" data-toggle="dropdown">@Html.Raw(menuItem.title)<span class="caret" data-toggle="dropdown"></span></a>
                                            <ul @menuItem.styles.GetSafeProperty("ulSubMenuClass" + "-" + @menuItemId)>
                                                @foreach (var childItem in menuItem.children)
                                                {
                                                    if (childItem.object_slug != null)
                                                    {
                                                        var routeValuesChild = new RouteValueDictionary();
                                                        routeValuesChild.Add("id", childItem.object_slug);
                                                        var menuItemIdChild = childItem.id.ToString();

                                                        <li @childItem.styles.GetSafeProperty("liBaseMenuId" + "-" + @menuItemIdChild) @Html.Raw(@childItem.styles.GetSafeProperty("liBaseMenuClass" + "-" + @menuItemIdChild))>
                                                            @Html.ActionLink(childItem.title, childItem.type_label, routeValuesChild)

                                                            @if (childItem.children != null && childItem.children.Any())
                                                            {
                                                                <!--Third Level Menu-->
                                                                <ul @childItem.styles.GetSafeProperty("ulSubMenuClass" + "-" + @menuItemIdChild)>
                                                                    @foreach (var subChildItem in childItem.children)
                                                                    {
                                                                        if (subChildItem.object_slug != null)
                                                                        {
                                                                            var routeValuesSubChild = new RouteValueDictionary();
                                                                            routeValuesSubChild.Add("id", subChildItem.object_slug);
                                                                            var menuItemIdSubChild = subChildItem.id.ToString();

                                                                            <li @subChildItem.styles.GetSafeProperty("liBaseMenuId" + "-" + @menuItemIdSubChild) @Html.Raw(subChildItem.styles.GetSafeProperty("liBaseMenuClass" + "-" + @menuItemIdSubChild))>
                                                                                @Html.ActionLink(subChildItem.title, subChildItem.type_label, routeValuesSubChild)
                                                                            </li>
                                                                        }
                                                                    }
                                                                </ul>
                                                            }
                                                        </li>
                                                    }

                                                }
                                            </ul>
                                        }

                                    </li>
                                }
                            }
                        </ul>

                    </div>
                }
                    </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>


WordPress/Views/MVC/_MVCLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My WordPress MVC Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Html.Partial("_WPHeadScripts")
</head>
<body>
    @Html.Partial("~/Views/MVC/_MVCHeader.cshtml")

    @Html.Partial("_WPSlider")

<div class="container body-content">
        @RenderBody()
        <hr />
    <footer>
        @Html.Partial("_WPFootNavMenu")
        <p>&copy; @DateTime.Now.Year - My WordPress MVC Application</p>
    </footer>
    </div>
    @Html.Partial("_WPFootScripts")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>